apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: planetarium-service-monitor
  labels:
    release: prometheus
    app: planetarium
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: planetarium
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 10s