prometheus:
  prometheusSpec: # this tells Prometheus to look for the service monitor/s with the given key/value labels
    # serviceMonitorNamespaceSelector: {default}
    serviceMonitorSelector:
      matchLabels:
        app: planetarium
        app: prometheus
        release: prometheus

grafana:
    namespaceOverride: "default"
    grafana.ini:
      smtp:
        enabled: "true"
        host: "smtp.gmail.com:465"
        user: "luis13314@gmail.com"
        password: "sbrzbnqbplyaeblg"
        skip_verify: "true"
        from_address: "luis13314@gmail.com"
        from_name: "Grafana"
      server:
        serve_from_sub_path: "true"
        root_url: "%(protocol)s://%(domain)s:/grafana/" # this lets Kubernetes auto set root_url value
#password is prom-operator
    ingress:
      enabled: true
      path: /grafana
      ingressClassName: nginx