apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: planetarium-prometheus-rules
  labels:
    release: prometheus
spec:
  groups:
  - name: AppDown
    rules:
    - alert: AppDown
      expr: up{job="planetarium-app"} != 1
      labels:
        severity: critical
      annotations:
        summary: "App is down"
        description: "Prometheus has detected the application is not running"

    - alert: APIHighLatency:5min
      expr: sum(rate(http_server_requests_seconds_sum{job="planetarium-clusterip"}[5m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[5m])) > 0.2
      labels:
        severity: warn
      annotations:
        summary: "5min latency too high"
        description: "Planetarium application is taking too long to handle requests in a 5 minute range"

    - alert: APIHighLatency:15min
      expr: sum(rate(http_server_requests_seconds_sum{job="planetarium-clusterip"}[15m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[15m])) > 0.2
      labels:
        severity: warn
      annotations:
        summary: "15min latency too high"
        description: "Planetarium application is taking too long to handle requests in a 15 minute range"

    - alert: APIHighLatency:30min
      expr: sum(rate(http_server_requests_seconds_sum{job="planetarium-clusterip"}[30m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[30m])) > 0.2
      labels:
        severity: warn
      annotations:
        summary: "30min latency too high"
        description: "Planetarium application is taking too long to handle requests in a 30 minute range"

    - alert: APIHighLatency:1hour
      expr: sum(rate(http_server_requests_seconds_sum{job="planetarium-clusterip"}[1h])) / sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[1h])) > 0.2
      labels:
        severity: warn
      annotations:
        summary: "1hour latency too high"
        description: "Planetarium application is taking too long to handle requests in an hour range"

    - alert: APILowSuccessRate:5min
      expr: sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip", status=~"5.."}[5m]))/sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[5m])) < 0.999
      labels:
        severity: warn
      annotations:
        summary: "5min success rate too low"
        description: "Planetarium application is experiencing too many status 500 codes in a 5 minute range"
    
    - alert: APILowSuccessRate:15min
      expr: sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip", status=~"5.."}[15m]))/sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[15m])) < 0.999
      labels:
        severity: warn
      annotations:
        summary: "15min success rate too low"
        description: "Planetarium application is experiencing too many status 500 codes in a 15 minute range"
      
    - alert: APILowSuccessRate:30min
      expr: sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip", status=~"5.."}[30m]))/sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[30m])) < 0.999
      labels:
        severity: warn
      annotations:
        summary: "30min success rate too low"
        description: "Planetarium application is experiencing too many status 500 codes in a 30 minute range"
    
    - alert: APILowSuccessRate:1hr
      expr: sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip", status=~"5.."}[1h]))/sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[1h])) < 0.999
      labels:
        severity: warn
      annotations:
        summary: "1hr success rate too low"
        description: "Planetarium application is experiencing too many status 500 codes in a 1 hour range"

    - alert: BurnRate:2%ErrorBudget
      expr: (sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip", status=~"5.."}[5m]))/sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[5m])) > 14.4*0.001) and (sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip", status=~"5.."}[1h]))/sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[1h])) >14.4*0.001)
      labels:
        severity: page
      annotations:
        summary: "Currently on a 2% Burn Rate"
        description: "Projected to use Error Budget at a burn rate of 2%."

    - alert: BurnRate:5%ErrorBudget
      expr: (sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip", status=~"5.."}[30m]))/sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[30m])) > 6*0.001) and (sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip", status=~"5.."}[6h]))/sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[6h])) >6*0.001)
      labels:
        severity: page
      annotations:
        summary: "Currently on a 5% Burn Rate"
        description: "Projected to use Error Budget at a burn rate of 5%."

    - alert: BurnRate:10%ErrorBudget
      expr: (sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip", status=~"5.."}[6h]))/sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[6h])) > 1*0.001) and (sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip", status=~"5.."}[3d]))/sum(rate(http_server_requests_seconds_count{job="planetarium-clusterip"}[3d])) >1*0.001)
      labels:
        severity: Ticket
      annotations:
        summary: "Currently on a 10% Burn Rate"
        description: "Projected to use Error Budget at a burn rate of 10%."

    

    